stages:
  - validate
  - test
  - build

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 10
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/lifecycle/.gradle"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lifecycle/.gradle/wrapper
    - lifecycle/.gradle/caches

checkstyle:
  stage: validate
  image: registry.harness.ai/eclipse-temurin:25-jdk
  script:
    - pwd
    - ./gradlew checkstyleMain checkstyleTest -s
    - ls 
  artifacts:
    paths:
      - build/reports/checkstyle/
    expire_in: 30 days
    when: always

pmd:
  stage: validate
  image: registry.harness.ai/eclipse-temurin:25-jdk
  script:
    - ./gradlew pmdMain pmdTest
  artifacts:
    paths:
      - build/reports/pmd/
    expire_in: 30 days
    when: always

unit-test:
  stage: test
  image: registry.harness.ai/eclipse-temurin:25-jdk
  script:
    - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build/reports/tests/test/
      - build/test-results/test/
    expire_in: 30 days
    when: always

jib-build:
  stage: build
  image: registry.harness.ai/eclipse-temurin:25-jdk
  script:
    - ./gradlew :harness-biz:lifecycle-biz:jib -PregistryUrl=$REGISTRY_URL -PregistryUsername=$REGISTRY_USERNAME -PregistryPassword=$REGISTRY_PASSWORD
  only:
    - main
    - tags
  except:
    - merge_requests
